// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	controller2 "github.com/echochat/backend/app/admin/controller"
	dao2 "github.com/echochat/backend/app/admin/dao"
	service2 "github.com/echochat/backend/app/admin/service"
	"github.com/echochat/backend/app/auth/controller"
	"github.com/echochat/backend/app/auth/dao"
	"github.com/echochat/backend/app/auth/service"
	"github.com/echochat/backend/app/ws"
	"github.com/echochat/backend/config"
	"github.com/echochat/backend/pkg/db"
)

// Injectors from wire.go:

// InitializeApp 初始化整个应用（Wire 自动生成实现）
func InitializeApp(cfg *config.Config) (*App, error) {
	databaseConfig := provideDBConfig(cfg)
	gormDB, err := db.NewPostgres(databaseConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideRedisConfig(cfg)
	client, err := db.NewRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	userDAO := dao.NewUserDAO(gormDB)
	roleDAO := dao.NewRoleDAO(gormDB)
	jwtConfig := provideJWTConfig(cfg)
	tokenStore := service.NewTokenStore(client, jwtConfig)
	authService := service.NewAuthService(userDAO, roleDAO, jwtConfig, tokenStore)
	authController := controller.NewAuthController(authService)
	adminAuthController := controller.NewAdminAuthController(authService)
	userManageDAO := dao2.NewUserManageDAO(gormDB)
	userManageService := service2.NewUserManageService(userManageDAO, userDAO, roleDAO)
	userManageController := controller2.NewUserManageController(userManageService)
	hub := ws.ProvideHub()
	pubSub := ws.ProvidePubSub(client, hub)
	handler := ws.ProvideWSHandler(hub, pubSub, jwtConfig)
	app := NewApp(cfg, gormDB, client, authService, authController, adminAuthController, userManageController, handler, hub, pubSub)
	return app, nil
}
